# Generated by Django 2.0.3 on 2018-03-30 02:02

from django.db import migrations


def add_initial_data(apps, schema_editor):

    User = apps.get_model('WebDNA', 'User')
    user = User.objects.create(
        username='jjmcpher',
        email='jjmcpher@uark.edu',
        first_name='Jace',
        last_name='McPherson',
        password='bcrypt_sha256$$2b$12$sAaLD8r12W7lqP6g4y50j.QRl4qgWsGlolgjWIDXbDZ1eBTywCVse'
    )
    user.save()

    Project = apps.get_model('WebDNA', 'Project')
    project = Project.objects.create(
        user=user,
        name='Project 1'
    )
    project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('WebDNA', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_data)
    ]
