# Generated by Django 2.0.2 on 2018-07-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdna', '0002_add_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='terminated',
            field=models.BooleanField(default=False),
        ),
    ]
