# Generated by Django 2.0.2 on 2018-04-03 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebDNA', '0003_allow_null_date_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='job_running',
        ),
    ]
