# Generated by Django 2.0.2 on 2018-04-26 07:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('WebDNA', '0004_remove_project_job_running'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file_name', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(default=None, max_length=280, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebDNA.User')),
            ],
            options={
                'db_table': '"webdna"."script"',
            },
        ),
    ]
